"""add intake_items table

Revision ID: 34e9447b098f
Revises: ad602c6d7387
Create Date: 2026-07-12 09:01:38.823511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34e9447b098f'
down_revision: Union[str, None] = 'ad602c6d7387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('new', 'opened', 'confirmed', 'rejected', 'archived', 'deleted', name='intake_status'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=False),
    sa.Column('source', postgresql.ENUM('camera', 'upload', name='intake_source'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intake_items')
    # ### end Alembic commands ###
