"""add updated_at to confirmed_products

Revision ID: 8c38a975ad3f
Revises: d4ae8480d5b0
Create Date: 2026-07-17 12:36:57.282911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c38a975ad3f'
down_revision: Union[str, None] = 'd4ae8480d5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmed_products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('confirmed_products', 'updated_at')
    # ### end Alembic commands ###
