"""add confirmed_products table

Revision ID: d4ae8480d5b0
Revises: cc1f3f6b805b
Create Date: 2026-07-12 13:52:22.641516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ae8480d5b0'
down_revision: Union[str, None] = 'cc1f3f6b805b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmed_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intake_item_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_name_source', sa.String(), nullable=False),
    sa.Column('product_name_override_reason', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('price_source', sa.String(), nullable=False),
    sa.Column('price_override_reason', sa.String(), nullable=True),
    sa.Column('ocr_raw_text', sa.String(), nullable=True),
    sa.Column('ocr_title_guess', sa.String(), nullable=True),
    sa.Column('ocr_title_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_price_guess', sa.String(), nullable=True),
    sa.Column('ocr_price_confidence', sa.Float(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intake_item_id'], ['intake_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intake_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmed_products')
    # ### end Alembic commands ###
